crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^messages/', include('privatemessages.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/accounts/login'}),
]

main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from main import views

urlpatterns = [
	# client side


	# admin
	url(r'^$', views.index, name='index'),
	url(r'^get_storage_price/$', views.get_storage_price, name='get_storage_price'),
	url(r'^add_delivery_status/$', views.add_delivery_status, name='add_delivery_status'),
	url(r'^delivery/$', views.delivery, name='delivery'),
	url(r'^delivery/(?P<pk>[0-9]+)/$', views.delivery_show, name='delivery_show'),
	url(r'^delivery/(?P<pk>[0-9]+)/edit/$', views.delivery_edit, name='delivery_edit'),
	url(r'^delivery/(?P<pk>[0-9]+)/status/$', views.delivery_status, name='delivery_status'),
	url(r'^storage/$', views.storage, name='storage'),
	url(r'^cash/$', views.cash, name='cash'),
	url(r'^create_goods/$', views.create_goods, name='create_goods'),
	url(r'^add_goods/(?P<goods_id>\d+)/$', views.add_goods, name='add_goods'),
	url(r'^remove_goods/(?P<goods_id>\d+)/$', views.remove_goods, name='remove_goods'),

	# asterisk cdr load
	#url(r'^main/sms/$', smssend, name='smssend'),
]

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q

class Service(models.Model):
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Shop(models.Model):
    url = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    directors_name = models.CharField(max_length=255)
    directors_phone = models.CharField(max_length=255)
    directors_email = models.CharField(max_length=255)
    servises = models.ManyToManyField(Service)
    last_calculation = models.DateTimeField()

    def servises_list(self):
        return ', '.join([a.name for a in self.servises.all()])

    def __unicode__(self):
        return self.alias

class Storage(models.Model):
    name = models.CharField(max_length=255)
    last_coming = models.DateTimeField()
    own_shop = models.ForeignKey(Shop)
    price = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

    def count_logs(self):
        storage_in = 0
        for item in StorageLog.objects.filter(storage=self, shop=self.own_shop, log_type__log_type='in'):
            storage_in = storage_in + item.count
        storage_out = 0
        for item in StorageLog.objects.filter(storage=self, shop=self.own_shop, log_type__log_type='out'):
            storage_out = storage_out + item.count
        return storage_in - storage_out

class StorageLogType(models.Model):
    """docstring for StorageLog"""
    name = models.CharField(max_length=255)
    log_type = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class StorageLog(models.Model):
    """docstring for StorageLog"""
    log_type = models.ForeignKey(StorageLogType)
    action = models.CharField(max_length=255)
    shop = models.ForeignKey(Shop)
    storage = models.ForeignKey(Storage)
    date = models.DateTimeField()
    count = models.IntegerField()

    def __unicode__(self):
        return self.action

class CashType(models.Model):
    name = models.CharField(max_length=255)
    type_code = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Cash(models.Model):
    sum = models.IntegerField()
    last_coming = models.DateTimeField()
    own_shop = models.ForeignKey(Shop)
    cash_type = models.ForeignKey(CashType)
    creator_url = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return str(self.sum)

class Courier(models.Model):
    """docstring for Сourier"""
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    comment = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Delivery(models.Model):
    """docstring for Delivery"""
    shop = models.ForeignKey(Shop, verbose_name='Магазин')
    date = models.DateTimeField()
    custom_product = models.CharField(max_length=255, blank=True)
    is_custom_product = models.BooleanField(default=0)
    custom_price = models.IntegerField(default=0, blank=True)
    is_custom_price = models.BooleanField(default=0)
    delivery_fromclient = models.IntegerField(default=0, blank=True, verbose_name='Стоимость с клиента')
    delivery_price = models.IntegerField(default=0, blank=True, verbose_name='Стоимость с партнера')
    delivery_date = models.DateField(verbose_name='Дата доставки')
    address = models.CharField(max_length=255, verbose_name='Адрес доставки')
    phone = models.CharField(max_length=255, verbose_name='Телфон')
    time = models.CharField(max_length=255, blank=True, verbose_name='Время')
    courier = models.ForeignKey(Courier, blank=True, null=True, verbose_name='Курьер')
    cash_in_transaction_id = models.IntegerField(default=0, blank=True)
    cash_out_transaction_id = models.IntegerField(default=0, blank=True)
    storage_in_transaction_id = models.IntegerField(default=0, blank=True)
    storage_out_transaction_id = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        return self.address

    def tel_addr_time(self):
        string = []
        if self.phone != '':
            string.append(self.phone)
        if self.address != '':
            string.append(self.address)
        if self.time != '':
            string.append(self.time)
        return ", ".join(string)

    def total_product(self):
        if self.custom_product == '':
            product = []
            for item in self.deliveryproduct_set.all():
                product.append(item.product.name)
            return ", ".join(product)
        else:
            return self.custom_product

    def total_price(self):
        if self.is_custom_price == False:
            price = 0
            for item in self.deliveryproduct_set.all():
                price = price + item.product.price*item.count
            return price    
        else:
            return self.custom_price

    def client_price(self):
        return self.total_price() + self.delivery_fromclient

    def to_partner(self):
        return self.total_price() - self.delivery_price + self.delivery_fromclient

class DeliveryProduct(models.Model):
    """docstring for DeliveryProduct"""
    product = models.ForeignKey(Storage)
    delivery = models.ForeignKey(Delivery)
    count = models.IntegerField(default=1)

    def __unicode__(self):
        return self.product.name

    def delivery_id(self):
        return str(delivery.pk)

class DeliveryStatus(models.Model):
    """docstring for DeliveryStatus"""
    status = models.CharField(max_length=200)
    code = models.CharField(max_length=10, unique=True)
    label = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return self.status

class DeliveryStatusList(models.Model):
    """docstring for DeliveryList"""
    status = models.ForeignKey(DeliveryStatus)
    delivery = models.ForeignKey(Delivery)
    date = models.DateTimeField()

    def __unicode__(self):
        return " | ".join([str(self.date), self.status.status, unicode(self.delivery.tel_addr_time())])

class DeliveryLog(models.Model):
    """docstring for DeliveryStatus"""
    name = models.CharField(max_length=200)
    date = models.DateTimeField()
    shop = models.ForeignKey(Shop)
    delivery = models.ForeignKey(Delivery)
    user = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name    

main/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required

from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.core.cache import cache
from django import forms

from datetime import datetime
import json
import logging

from main.models import (
    Shop,
    Storage,
    StorageLog,
    StorageLogType,
    Delivery,
    DeliveryProduct,
    Cash,
    CashType,
    DeliveryStatusList,
    DeliveryStatus,
    DeliveryLog,
)
from main.forms import DeliveryForm, DeliveryProductFormSet

now = datetime.now()
logger = logging.getLogger('user') # пользовательский логгер для бебага


def index(request):
    delivery = Delivery.objects.all().order_by('-date')

    context = {
        'delivery': delivery,
    }

    return render(request, 'dashboard.html', context)

def create_goods(request):
    if request.method == "POST":
        own_shop = Shop.objects.get(alias=request.POST['own_shop'])
        storage = Storage(
            name = request.POST['name'],
            price = request.POST['price'],
            own_shop = own_shop,
            last_coming = now.strftime('%Y-%m-%d %H:%M:%S')
        )
        storage.save()

        if request.POST['count']:
            storagelog = StorageLog(
                log_type = StorageLogType.objects.get(pk=3),
                action = "Создан новый товар: "+request.POST['name'].encode('utf-8')+" с начальным остатком: "+request.POST['count'].encode('utf-8')+" шт.",
                shop = own_shop,
                storage = storage,
                date = now.strftime('%Y-%m-%d %H:%M:%S'),
                count = int(request.POST['count'])
            )
            storagelog.save()

        return HttpResponseRedirect('/storage/')

    raise Http404

def add_goods(request, goods_id):
    if request.method == "POST":
        now = datetime.now()
        goods = Storage.objects.get(pk=goods_id)
        storagelog = StorageLog(
            log_type = StorageLogType.objects.get(pk=1),
            action = "Поступление товара: "+goods.name.encode('utf-8')+" в количестве: "+request.POST['count'].encode('utf-8')+" шт.",
            shop = goods.own_shop,
            storage = goods,
            date = now.strftime('%Y-%m-%d %H:%M:%S'),
            count = int(request.POST['count'])
        )
        storagelog.save()

        return HttpResponseRedirect('/storage/')

    raise Http404

def remove_goods(request, goods_id):
    if request.method == "POST":
        now = datetime.now()
        goods = Storage.objects.get(pk=goods_id)
        storagelog = StorageLog(
            log_type = StorageLogType.objects.get(pk=2),
            action="Списание товара: "+goods.name.encode('utf-8')+" в количестве: "+request.POST['count'].encode('utf-8')+" шт.",
            shop = goods.own_shop,
            storage = goods,
            date = now.strftime('%Y-%m-%d %H:%M:%S'),
            count = int(request.POST['count'])
        )
        storagelog.save()

        return HttpResponseRedirect('/storage/')

    raise Http404


def storage(request):
    goods_list = Storage.objects.all()
    shops_list = Shop.objects.all()
    logs_list = StorageLog.objects.all().order_by('-date')

    context = {
        'goods_list': goods_list,
        'shops_list': shops_list,
        'logs_list': logs_list
    }

    return render(request, 'storage.html', context)

def cash(request):
    cash = Cash.objects.all().order_by('-last_coming')

    context = {
        'cash': cash,
    }

    return render(request, 'cash.html', context)

def get_storage_price(request):
    if request.is_ajax():
        #storage = Storage.objects.get
        #product = Menu.objects.get(id=product_id)
        #cart = Cart(request)
        price = 0
        received_json_data = json.loads(request.body)
        if received_json_data != None:
            for pk in received_json_data:
                product = Storage.objects.get(id=pk)
                price += product.price

        response_data = {}
        response_data['result'] = price
        return HttpResponse(json.dumps(response_data), content_type='application/json')

    return HttpResponse("Это работает не так :(")


"""add_delivery_status functions"""
""""""
def delete_cache_fn(cache_id):
    try:
        cash = Cash.objects.get(pk=cache_id)
        cash.delete()
        return cash
    except Exception as e:
        return 0

def add_to_cache_fn(creator_url, sum, delivery, action):
    cash = Cash(
        creator_url = creator_url,
        sum = sum,
        last_coming = now.strftime('%Y-%m-%d %H:%M'),
        own_shop = delivery.shop,
        cash_type = get_object_or_404(CashType, type_code=action),
    )
    cash.save()
    return cash

def add_delivery_status_fn(status_id, delivery_id):
    status = DeliveryStatusList(
        status = get_object_or_404(DeliveryStatus, code=status_id),
        delivery = get_object_or_404(Delivery, pk=delivery_id),
        date = now.strftime('%Y-%m-%d %H:%M')
    )
    status.save()

    if status.status.code == "1":
        if status.delivery.cash_in_transaction_id != 0 and status.delivery.cash_out_transaction_id != 0:
            cash_in = delete_cache_fn(status.delivery.cash_in_transaction_id)
            cash_out = delete_cache_fn(status.delivery.cash_out_transaction_id)
        status.delivery.cash_in_transaction_id = 0
        status.delivery.cash_out_transaction_id = 0
        status.delivery.save()

    if status.status.code == "4" and status.delivery.cash_in_transaction_id == 0 and status.delivery.cash_out_transaction_id == 0:
        cash_in = add_to_cache_fn('/delivery/'+str(status.delivery.id)+'/', status.delivery.client_price(), status.delivery, 'in')
        cash_out = add_to_cache_fn('/delivery/'+str(status.delivery.id)+'/', status.delivery.delivery_price, status.delivery, 'out')
        status.delivery.cash_in_transaction_id = cash_in.id
        status.delivery.cash_out_transaction_id = cash_out.id
        status.delivery.save()

    if status.status.code == "5" and status.delivery.cash_in_transaction_id != 0 and status.delivery.cash_out_transaction_id != 0:
        cash_in = delete_cache_fn(status.delivery.cash_in_transaction_id)
        cash_out = delete_cache_fn(status.delivery.cash_out_transaction_id)
        status.delivery.cash_in_transaction_id = 0
        status.delivery.cash_out_transaction_id = 0
        status.delivery.save()

    if status.status.code == "6":
        if status.delivery.cash_in_transaction_id == 0 and status.delivery.cash_out_transaction_id == 0:
            cash_in = add_to_cache_fn('/delivery/'+str(status.delivery.id)+'/', 0, status.delivery, 'in')
            cash_out = add_to_cache_fn('/delivery/'+str(status.delivery.id)+'/', status.delivery.delivery_price, status.delivery, 'out')
            status.delivery.cash_in_transaction_id = cash_in.id
            status.delivery.cash_out_transaction_id = cash_out.id
            status.delivery.save()

    return status
""""""
"""/add_delivery_status functions"""

def add_delivery_status(request):
    if request.is_ajax():
        if request.POST.get('value') and request.POST.get('delivery'):
            new_status = add_delivery_status_fn(request.POST.get('value'), request.POST.get('delivery'))

            response_data = {}
            response_data['result'] = str(new_status.status)
            response_data['code'] = str(new_status.status.code)
            response_data['label'] = str(new_status.status.label)
            return HttpResponse(json.dumps(response_data), content_type='application/json')

    return HttpResponse("Это работает не так :(")

def delivery(request):
    delivery = Delivery.objects.all().order_by('-date')
    status = DeliveryStatus.objects.all()
    deliverylog = DeliveryLog.objects.all().order_by('-date')

    
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DeliveryForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            if form.cleaned_data['is_custom_product']:
                custom_product = form.cleaned_data['custom_product']
            else:
                custom_product = ''

            if form.cleaned_data['is_custom_price']:
                custom_price = form.cleaned_data['custom_price']
                #custom_price = cleaned_data['is_custom_price']
            else:
                custom_price = 0
            
            if (form.cleaned_data['delivery_fromclient'] == '' or form.cleaned_data['delivery_fromclient'] == None):
                delivery_fromclient = 0
            else:
                delivery_fromclient = form.cleaned_data['delivery_fromclient']

            created_delivery = form.save(commit=False)

            created_delivery.date = now.strftime('%Y-%m-%d %H:%M')
            created_delivery.custom_product = custom_product
            created_delivery.custom_price = custom_price
            created_delivery.delivery_fromclient = delivery_fromclient
            
            formset = DeliveryProductFormSet(request.POST, instance=created_delivery)

            if formset.is_valid():
                created_delivery.save()
                formset.save()

                new_status = DeliveryStatusList(
                    status = get_object_or_404(DeliveryStatus, code=1),
                    delivery = get_object_or_404(Delivery, pk=created_delivery.pk),
                    date = now.strftime('%Y-%m-%d %H:%M')
                )
                new_status.save()
                # redirect to a new URL:
                return HttpResponseRedirect('/delivery/')
            #else:
            #    return HttpResponse("Ошибка второй формы"+str(formset.errors))

        #else:

main/templates/delivery_status.html
{% extends "base.html" %}

{% load myfilters %}

{% block delivery %}class="active"{% endblock %}  {% block delivery-span %}<span class="sr-only">(current)</span>{% endblock %}

{% block content %}
        <script>

            $(document).ready( function () {

                var myDate = new Date();
                var displayTime = (myDate.getHours()<10?'0':'') + myDate.getHours() + ':' + (myDate.getMinutes()<10?'0':'') + myDate.getMinutes() + ':' + (myDate.getSeconds()<10?'0':'') + myDate.getSeconds();

                $("input[type=submit], a, button").button();
                //$('input').addClass("text ui-widget-content ui-corner-all");
                //$('#add_new_goods').dialog();
                
                /* НАЧАЛО Приход товаров */
                $(".add-goods-btn").on("click", function() {
                    var add_dialog = $("#add-goods");
                    var action = add_dialog.find('form').attr("action");
                    action = action.replace("$", $(this).attr("id"));
                    add_dialog.find("form").attr("action", action);
                    add_dialog.find("#add-goods-time").val(displayTime);
                    add_dialog.modal();
                });
                /* КОНЕЦ Приход товаров */

                /* НАЧАЛО Списание товаров */
                $(".remove-goods-btn").on("click", function() {
                    var remove_dialog = $("#remove-goods");
                    var action = remove_dialog.find('form').attr("action");
                    action = action.replace("$", $(this).attr("id"));
                    remove_dialog.find("form").attr("action", action);
                    remove_dialog.find("#remove-goods-time").val(displayTime);
                    remove_dialog.modal();
                });
                /* КОНЕЦ Списание товаров */

                $("#id_delivery_date").datepicker({
                    language: 'ru',
                    format: 'yy-mm-dd',
                    dateFormat: 'yy-mm-dd',
                }).on("show", function() {
                    $(this).val("{{ form.delivery_date.value }}").datepicker('update');
                });
                //$("#id_delivery_date").datepicker("option", "dateFormat", "yy-mm-dd");
                //$("#id_delivery_date").val("").datepicker('update');

                //$("#own_shop").selectmenu();
                

                $('#storage').DataTable({
                    "language": {
                        "search": "Поиск:",
                        "lengthMenu": "Показывать по _MENU_ записей на странице",
                        "info": "Отображается  страница _PAGE_ из _PAGES_",
                        "infoEmpty": "Отображено с 0 по 0 из 0 записей",
                        "zeroRecords": "Не найдено результатов",
                        "paginate": {
                            "first":      "Первая",
                            "last":       "Последняя",
                            "next":       "Вперед",
                            "previous":   "Назад"
                        },
                    }
                });

                $("input[name=is_custom_product]").on('change', function() {
                    //console.log($(this).attr('id'));
                    if ($(this).attr('id') == 'id_is_custom_product_0') {
                        $('#id_custom_product').attr('disabled', '');
                        $('#id_custom_price').attr('disabled', '');
                        $('#id_is_custom_price' ).prop('checked', false );
                        $("#id_storage_product").prop('disabled', false).trigger('chosen:updated');
                        $('#id_is_custom_price' ).removeAttr('disabled');
                    }
                    if ($(this).attr('id') == 'id_is_custom_product_1') {
                        $('#id_custom_product').removeAttr('disabled');
                        $('#id_custom_price').removeAttr('disabled');
                        $('#id_is_custom_price' ).prop('checked', true );
                        $("#id_storage_product").prop('disabled', true).trigger('chosen:updated');
                        $('#id_is_custom_price' ).attr('disabled', '');
                    }
                });

                $("input[name=is_custom_price]").on('change', function() {
                    if ($(this).prop('checked')) {
                        $('#id_custom_price').removeAttr('disabled');
                    } else {
                        $('#id_custom_price').attr('disabled', '');
                    }
                });
                //$("#id_storage_product").addClass('form-control');
                $("#id_storage_product").chosen({allow_single_deselect:true});

                $('#id_storage_product').on('change', function(event, params) {
                    if(event.target == this){
                        pk_list = $(this).val();
                    }



                    $.ajax({
                        url: '/get_storage_price/',
                        type: 'POST',
                        data: JSON.stringify(pk_list),
                        dataType: 'json',
                        beforeSend: function (xhr, settings) {
                            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                            }
                        },
                        success: function () {

                        }
                    }).done(function(data) {
                        $("#storage-product-price").html('<span style="margin-top: 12px;display: inline-block;">Цена склада:&nbsp;</span><span>'+data.result+' р. </span>');
                    });


                });



            });

        </script>
        <div class="panel panel-default">
            <div class="panel-heading">Детали доставки № <span class="label label-default" style="">{{ delivery.id }}</span> | {{ delivery.date|date:"Y-m-d H:i" }}</div>
            <div class="panel-body">
                <div class="content-tabs" >

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation"><a href="{% url 'delivery_edit' delivery.id %}">Детали</a></li>
                        <li role="presentation" class="active"><a href="{% url 'delivery_status' delivery.id %}">Статусы</a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="status">
                            
                            <div class="row">
                                <div class="col-lg-6">
                                    <table class="table">
                                        <thead>
                                            <tr><th>Дата</th><th>Статус</th></tr>
                                        </thead>
                                        {% for status in statuslist %}
                                        <tr>
                                            <td>{{ status.date }}</td><td>{{ status.status }}</td>
                                            <td>
                                                <button class="btn btn-danger delete" data-type="POST" data-url="/main/request/{{ requestobj.id }}/status/delete/{{ status.id }}">
                                                    <i class="glyphicon glyphicon-trash"></i>
                                                    <span>Удалить</span>
                                                </button>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                                <div class="col-lg-6">
                                    <form id="" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                                        <select class="form-control" name="status">
                                            {% for item in status %}
                                            <option value="{{ item.id }}">{{ item.status }}</option>
                                            {% endfor %}
                                        </select>
                                        <input name="add_status" class="btn btn-success" type="submit" value="Добавить" style="margin-right:0px;" multiple>
                                    </form>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}